### ISSUE TITLE
Crash (not running strange)

### ISSUE THREAD

**Issue by WhiskyTangoFawks** [svenhjol/Charmonium#1]
Hiya, got the following crash report while running Quark, Charm, Charmium, but NOT Strange

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 06-06-2020 19:44
Description: Ticking entity

java.lang.NoClassDefFoundError: svenhjol/strange/Strange
	at svenhjol.charmonium.ambience.client.ambience.CaveAmbientSounds$CrystalCaves.getShortSoundDelay(CaveAmbientSounds.java:79) ~[?:1.15.2-1.0.0] {re:classloading}
	at svenhjol.charmonium.ambience.client.ambience.BaseAmbientSounds.tick(BaseAmbientSounds.java:40) ~[?:1.15.2-1.0.0] {re:classloading}
	at svenhjol.charmonium.ambience.client.AmbientSoundClient$Handler$$Lambda$5474/64041371.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at svenhjol.charmonium.ambience.client.AmbientSoundClient$Handler.tick(AmbientSoundClient.java:82) ~[?:1.15.2-1.0.0] {re:classloading}
	at svenhjol.charmonium.ambience.module.Sounds.onPlayerTick(Sounds.java:54) ~[?:1.15.2-1.0.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_100_Sounds_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPostTick(BasicEventHooks.java:89) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:280) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:PlayerEntity,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:235) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.world.ClientWorld$$Lambda$5472/1735099891.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:196) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1398) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:904) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.2.0.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$471/1506703662.call(Unknown Source) [forge-1.15.2-31.2.0.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}
Caused by: java.lang.ClassNotFoundException: svenhjol.strange.Strange
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at svenhjol.charmonium.ambience.client.ambience.CaveAmbientSounds$CrystalCaves.getShortSoundDelay(CaveAmbientSounds.java:79)
	at svenhjol.charmonium.ambience.client.ambience.BaseAmbientSounds.tick(BaseAmbientSounds.java:40)
	at svenhjol.charmonium.ambience.client.AmbientSoundClient$Handler$$Lambda$5474/64041371.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at svenhjol.charmonium.ambience.client.AmbientSoundClient$Handler.tick(AmbientSoundClient.java:82)
	at svenhjol.charmonium.ambience.module.Sounds.onPlayerTick(Sounds.java:54)
	at net.minecraftforge.eventbus.ASMEventHandler_100_Sounds_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPostTick(BasicEventHooks.java:89)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:280)
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:235)
	at net.minecraft.client.world.ClientWorld$$Lambda$5472/1735099891.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.ClientPlayerEntity)
	Entity ID: 478
	Entity Name: Whiskytangofawks
	Entity's Exact location: 275.01, 63.89, 1228.54
	Entity's Block location: World: (275,63,1228), Chunk: (at 3,3,12 in 17,76; contains blocks 272,0,1216 to 287,255,1231), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Entity's Momentum: -0.08, -0.59, 0.14
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:196)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Whiskytangofawks'/478, l='MpServer', x=275.01, y=63.89, z=1228.54]]
	Chunk stats: Client Chunk Cache: 289, 143
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 6420008576066811976
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (26308,136,-454), Chunk: (at 4,8,10 in 1644,-29; contains blocks 26304,0,-464 to 26319,255,-449), Region: (51,-1; contains chunks 1632,-32 to 1663,-1, blocks 26112,0,-512 to 26623,255,-1)
	Level time: 129458 game time, 2565 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$471/1506703662.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2486993648 bytes (2371 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseG1GC -Xmx4G -Xms4G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre18.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.0.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.0
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.0-client.jar Minecraft {minecraft@1.15.2 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		gravestone_lite-1.15.2-1.0.2.jar GraveStone Lite {gravestone_lite@1.15.2-1.0.2 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		VTweaks-1.15.2-3.1.6.jar V-Tweaks {vtweaks@3.1.5 DONE}
		lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar Lithium {lithium@0.4.6-rc3 DONE}
		forge-1.15.2-31.2.0-universal.jar Forge {forge@31.2.0 DONE}
		SoundFilters-0.13_for_1.15.2.jar Sound Filters {soundfilters@0.13_for_1.15.2 DONE}
		overloadedarmorbar-4.0.0.jar Overloaded Armor Bar {overloadedarmorbar@4.0.0 DONE}
		Xaeros_Minimap_FP20.11.0_Forge_1.15.2.jar Xaero's Minimap Fair-Play {xaerominimap@20.11.0 DONE}
		XaerosWorldMap_1.5.7_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.7 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-237.jar Quark {quark@r2.1-237 DONE}
		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 DONE}
		Charmonium-1.15.2-1.0.0.jar Charmonium {charmonium@1.15.2-1.0.0 DONE}
	Launched Version: 1.15.2-forge-31.2.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.7810, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre18
	OptiFine Build: 20200519-182630
	Render Distance Chunks: 6
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7810
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by svenhjol** [comment]
My bad! Left some old references in.
Here's an updated version on CF: [https://www.curseforge.com/minecraft/mc-mods/charmonium/files/2974114](https://www.curseforge.com/minecraft/mc-mods/charmonium/files/2974114).

Thanks for the report :)
