### ISSUE TITLE
Crash at the start

### ISSUE THREAD

**Issue by DamienBrittan** [svenhjol/Charmonium#13]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 12/17/20 8:53 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4795/1233800546.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(SourceFile:404) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4581/1864931112.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.13.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$491/345780740.call(Unknown Source) [forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at svenhjol.charmonium.Charmonium.<init>(Charmonium.java:19) ~[?:2.1.9] {re:classloading}
-- MOD charmonium --
Details:
	Mod File: charmonium-forge-1.16.4-2.1.9.jar
	Failure message: Charmonium (charmonium) has failed to load correctly
		java.lang.NoSuchFieldError: INSTANCE
	Mod Version: 2.1.4
	Mod Issue URL: http://github.com/svenhjol/Charm/issues
	Exception message: java.lang.NoSuchFieldError: INSTANCE
Stacktrace:
	at svenhjol.charmonium.Charmonium.<init>(Charmonium.java:19) ~[?:2.1.9] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:35.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3076/1158611509.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3135/1839548688.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 864780416 bytes (824 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.13.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.13
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.13-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |CREATE_REG|NOSIGNATURE
		AmbientSounds_v3.1.4_mc1.16.4.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |CREATE_REG|NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.425-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.424   |CREATE_REG|NOSIGNATURE
		baubles-1.8.5-1.16.4.jar                          |Baubles                       |baubles                       |1.8.5               |CREATE_REG|NOSIGNATURE
		ShoulderSurfing-1.16.4-2.0.2.jar                  |Shoulder Surfing              |shouldersurfing               |1.16.4-2.0.2        |CREATE_REG|NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |CREATE_REG|NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.4.jar                 |CreativeCore                  |creativecore                  |2.0.0               |CREATE_REG|NOSIGNATURE
		fishingreal-1.16.3-1.0.0.jar                      |Fishing Real                  |fishingreal                   |1.0.0               |CREATE_REG|NOSIGNATURE
		abnormals_core-1.16.4-3.0.3.jar                   |Abnormals Core                |abnormals_core                |3.0.3               |CREATE_REG|NOSIGNATURE
		xercamod-1.16.4-1.0.jar                           |Xerca Mod                     |xercamod                      |1.16.4-1.0          |CREATE_REG|NOSIGNATURE
		caelus-forge-1.16.4-2.1.0.0.jar                   |Caelus API                    |caelus                        |1.16.4-2.1.0.0      |CREATE_REG|NOSIGNATURE
		charmonium-forge-1.16.4-2.1.9.jar                 |Charmonium                    |charmonium                    |2.1.4               |ERROR     |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.0.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.0      |CREATE_REG|NOSIGNATURE
		BetterCaves-1.16.3-1.0.6.jar                      |YUNG's Better Caves           |bettercaves                   |1.16.3-1.0.6        |CREATE_REG|NOSIGNATURE
		LotTweaks-mc1.16.4-version-1.3.0.jar              |LotTweaks                     |lottweaks                     |1.3.0               |CREATE_REG|NOSIGNATURE
		leap-1.16.4-1.0.1.jar                             |Leap                          |leap                          |1.0.1               |CREATE_REG|NOSIGNATURE
		carrotslib-mc1.16.4-3.0b1.jar                     |Carrots Lib                   |carrots                       |3.0b1               |CREATE_REG|NOSIGNATURE
		comforts-forge-1.16.4-4.0.0.2.jar                 |Comforts                      |comforts                      |1.16.4-4.0.0.2      |CREATE_REG|NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |CREATE_REG|NOSIGNATURE
		SereneSeasons-1.16.4-4.0.0.78-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.4-4.0.0.76     |CREATE_REG|NOSIGNATURE
		backpacked-1.7.0-1.16.3.jar                       |Backpacked                    |backpacked                    |1.7.0               |CREATE_REG|NOSIGNATURE
		decorative_blocks-1.16.4-1.6.0.jar                |Decorative Blocks             |decorative_blocks             |1.6.0               |CREATE_REG|NOSIGNATURE
		branders-spawnermod-1.16.4-1.7.9.jar              |Enhanced Mob Spawners         |spawnermod                    |1.7.10              |CREATE_REG|NOSIGNATURE
		Bookshelf-1.16.4-9.3.18.jar                       |Bookshelf                     |bookshelf                     |9.3.18              |CREATE_REG|ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		BotanyPots-1.16.4-6.0.7.jar                       |BotanyPots                    |botanypots                    |6.0.7               |CREATE_REG|ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		guardvillagers-1.16.3-1.1.5.jar                   |Guard Villagers               |guardvillagers                |1.1.5               |CREATE_REG|NOSIGNATURE
		treemendous-1.16.4-0.4.3.jar                      |Treemendous                   |treemendous                   |0.4.3               |CREATE_REG|NOSIGNATURE
		curiouselytra-forge-1.16.3-4.0.0.1.jar            |Curious Elytra                |curiouselytra                 |1.16.3-4.0.0.1      |CREATE_REG|NOSIGNATURE
		ItemPhysic_v1.4.12_mc1.16.4.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |CREATE_REG|NOSIGNATURE
		The_Undergarden-1.16.3-0.3.8.jar                  |The Undergarden               |undergarden                   |0.3.8               |CREATE_REG|NOSIGNATURE
		carryon-1.16.3-1.15.1.7.jar                       |Carry On                      |carryon                       |1.15.1.7            |CREATE_REG|8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		byg-1.1.5.jar                                     |Oh The Biomes You'll Go       |byg                           |1.1.5               |CREATE_REG|NOSIGNATURE
		chat_heads_forge-0.2.0.jar                        |Chat Heads                    |chat_heads                    |0.2.0               |CREATE_REG|NOSIGNATURE
		charm-forge-1.16.4-2.1.1-hotfix3.jar              |Charm                         |charm                         |2.1.1               |CREATE_REG|NOSIGNATURE
		forge-1.16.4-35.1.13-universal.jar                |Forge                         |forge                         |35.1.13             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Aquaculture-1.16.4-2.1.7.jar                      |Aquaculture 2                 |aquaculture                   |1.16.4-2.1.7        |CREATE_REG|NOSIGNATURE
		amb-1.16.4-0.1.1.jar                              |Aurum's More Blocks           |amb                           |1.16.4-0.1.1        |CREATE_REG|NOSIGNATURE
		CosmeticArmorReworked-1.16.4-v1.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.4-v1           |CREATE_REG|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		supplementaries-0.9.11.jar                        |Supplementaries               |supplementaries               |0.9.11              |CREATE_REG|NOSIGNATURE
		BetterMineshafts-Forge-1.16.3-1.1.jar             |YUNG's Better Mineshafts      |bettermineshafts              |1.16.3-1.1          |CREATE_REG|NOSIGNATURE
		corpse-1.16.4-1.0.4.jar                           |Corpse                        |corpse                        |1.16.4-1.0.4        |CREATE_REG|NOSIGNATURE
		chocolate-1.1.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.1.0-1.16.4        |CREATE_REG|NOSIGNATURE
		anviltweaks-3.1.jar                               |Anvil Tweaks                  |anviltweaks                   |3.1                 |CREATE_REG|NOSIGNATURE
	Crash Report UUID: 7e71ce07-8a36-4c38-88c9-6dfc64c74ea8

**Comment by svenhjol** [comment]
Your version of charm (2.1.1-hotfix3) is out of date and you need the latest version (2.1.9)

**Comment by DamienBrittan** [comment]
Thanks for quick answer <3
