### ISSUE TITLE
Crash on startup (1.19.3 Fabric)

### ISSUE THREAD

**Issue by Owehttamy** [svenhjol/Charmonium#60]
Appears that you can't run Charmonium on Fabric 1.19.3
Here's the crash log:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'charmonium'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoSuchFieldError: field_11142
		at ru.tpsd.eatinganimationmod.EatingAnimationClientMod.<clinit>(EatingAnimationClientMod.java:19)
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:467)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Suppressed: java.lang.ExceptionInInitializerError
		at foundationgames.enhancedblockentities.EBESetup.setupChests(EBESetup.java:246)
		at foundationgames.enhancedblockentities.EnhancedBlockEntities.load(EnhancedBlockEntities.java:51)
		at foundationgames.enhancedblockentities.EnhancedBlockEntities.onInitializeClient(EnhancedBlockEntities.java:32)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1059 failed
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
		at net.minecraft.class_4668.<clinit>(class_4668.java:259)
		... 12 more
	Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
		... 17 more
	Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [citresewn-defaults.mixins.json:common.SpriteAtlasTextureMixin from mod citresewn-defaults] from phase [DEFAULT] in config [citresewn-defaults.mixins.json] FAILED during APPLY
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
		... 20 more
	Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_32957 was not located in the target class net.minecraft.class_1059. Using refmap citresewn-defaults-refmap.json
		at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624)
		at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
		at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
		at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
		... 20 more
	Suppressed: java.lang.NoSuchMethodError: 'void net.minecraft.class_3414.<init>(net.minecraft.class_2960)'
		at dev.stashy.extrasounds.sounds.SoundRegistry.register(SoundRegistry.java:12)
		at dev.stashy.extrasounds.sounds.SoundRegistry.register(SoundRegistry.java:28)
		at dev.stashy.extrasounds.sounds.Categories.<clinit>(Categories.java:7)
		at dev.stashy.extrasounds.ExtraSounds.onInitializeClient(ExtraSounds.java:26)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at net.fabricmc.fabric.api.renderer.v1.material.BlendMode.<clinit>(BlendMode.java:33)
		at link.infra.indium.renderer.RenderMaterialImpl.<clinit>(RenderMaterialImpl.java:34)
		at link.infra.indium.renderer.IndiumRenderer.materialFinder(IndiumRenderer.java:49)
		at link.infra.indium.renderer.IndiumRenderer.<clinit>(IndiumRenderer.java:32)
		at link.infra.indium.Indium.onInitializeClient(Indium.java:124)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Suppressed: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'client' provided by 'voicechat'
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.reflect.InvocationTargetException
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:60)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		... 9 more
	Caused by: java.lang.reflect.InvocationTargetException
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:58)
		... 11 more
	Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3255 failed
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
		at java.base/java.lang.ClassLoader.defineClass1(Native Method)
		at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
		at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
		at de.maxhenkel.voicechat.VoicechatClient.<init>(VoicechatClient.java:34)
		at de.maxhenkel.voicechat.FabricVoicechatClientMod.<init>(FabricVoicechatClientMod.java:13)
		... 17 more
	Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
		... 31 more
	Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [citresewn.mixins.json:broken_paths.AbstractFileResourcePackMixin from mod citresewn] from phase [DEFAULT] in config [citresewn.mixins.json] FAILED during APPLY
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
		... 34 more
	Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_14181 was not located in the target class net.minecraft.class_3255. Using refmap CITResewn-refmap.json
		at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624)
		at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
		at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
		at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
		... 34 more
Caused by: java.lang.NoSuchFieldError: field_11156
	at svenhjol.charmonium.registry.ClientRegistry.sound(ClientRegistry.java:16)
	at svenhjol.charmonium.module.biome_ambience.sounds.Beach.register(Beach.java:23)
	at svenhjol.charmonium.module.biome_ambience.BiomeAmbience.register(BiomeAmbience.java:49)
	at svenhjol.charmonium.loader.ModuleLoader.lambda$register$0(ModuleLoader.java:45)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at svenhjol.charmonium.loader.ModuleLoader.register(ModuleLoader.java:42)
	at svenhjol.charmonium.loader.ModuleLoader.init(ModuleLoader.java:32)
	at svenhjol.charmonium.Charmonium.onInitializeClient(Charmonium.java:17)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)

```

**Comment by Owehttamy** [comment]
I updated the crash report, as other mods I used were having issues, adding red herrings.
The report now reflects what occurs when using the current latest Fabric launcher (0.14.12) and API (0.69.1) with only Charmonium; there are no outside conflicts.

**Comment by JunkynioyPH** [comment]
This also applies to FabricLauncher 0.14.12 + Fabric API 0.70.0

**Comment by EGOIST1372** [comment]
// I bet Cylons wouldn't have this problem.

Time: 2023-01-13 03:12:56
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'charmonium'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: field_11156
	at svenhjol.charmonium.registry.ClientRegistry.sound(ClientRegistry.java:16)
	at svenhjol.charmonium.module.biome_ambience.sounds.Beach.register(Beach.java:23)
	at svenhjol.charmonium.module.biome_ambience.BiomeAmbience.register(BiomeAmbience.java:49)
	at svenhjol.charmonium.loader.ModuleLoader.lambda$register$0(ModuleLoader.java:45)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at svenhjol.charmonium.loader.ModuleLoader.register(ModuleLoader.java:42)
	at svenhjol.charmonium.loader.ModuleLoader.init(ModuleLoader.java:32)
	at svenhjol.charmonium.Charmonium.onInitializeClient(Charmonium.java:17)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)
Mixins in Stacktrace:
	net.minecraft.class_310:
		ca.fxco.memoryleakfix.mixin.hugeScreenshotLeak.MinecraftClient_screenshotMixin (memoryleakfix.mixins.json)
		net.raphimc.immediatelyfast.injection.mixins.hud_batching.MixinMinecraftClient (immediatelyfast.mixins.json)
		dzwdz.chat_heads.mixin.MinecraftMixin (chat_heads.mixins.json)
		io.grayray75.fabric.fpsdisplay.mixin.MinecraftClientMixin (fpsdisplay.mixins.json)
		dev.hephaestus.atmosfera.mixin.MinecraftClientMixin (atmosfera.mixins.json)
		de.keksuccino.auudio.mixin.client.MixinMinecraft (auudio.mixin.json)
		com.replaymod.core.mixin.MixinMinecraft (mixins.core.replaymod.json)
		com.tterrag.blur.mixin.MixinMinecraftClient (mixins.blur.json)
		io.wispforest.owo.mixin.ui.MinecraftClientMixin (owo.mixins.json)
		dev.tr7zw.exordium.mixin.MinecraftMixin (exordium.mixins.json)
		de.keksuccino.konkrete.mixin.mixins.client.MixinMinecraft (konkrete.mixin.json)
		de.maxhenkel.status.mixin.MinecraftMixin (status.mixins.json)
		ca.fxco.memoryleakfix.mixin.targetEntityLeak.MinecraftClient_targetClearMixin (memoryleakfix.mixins.json)
		net.darkhax.bookshelf.mixin.client.AccessorMinecraft (bookshelf.common.mixins.json)
		de.maxhenkel.camerautils.mixin.MinecraftMixin (camerautils.mixins.json)
		de.keksuccino.fancymenu.mixin.client.MixinMinecraft (fancymenu.general.mixin.json)
		fi.dy.masa.minihud.mixin.MixinMinecraftClient (mixins.minihud.json)
		dlovin.inventoryhud.mixin.PlayerMixin (inventoryhud.mixins.json)
		de.keksuccino.fancymenu.mixin.client.IMixinMinecraft (fancymenu.general.mixin.json)
		io.wispforest.owo.mixin.MinecraftClientMixin (owo.mixins.json)
		me.jellysquid.mods.sodium.mixin.workarounds.issue1486.MixinMinecraftClient (sodium.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		dev.stashy.extrasounds.mixin.inventory.InventoryScreenSounds (extrasounds.mixins.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (fallingleaves.mixins.json)
		com.blamejared.controlling.mixin.OpenGuiMixin (controlling.fabric.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		fuzs.forgeconfigapiport.mixin.client.MinecraftMixin (forgeconfigapiport.common.mixins.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
		dev.stashy.extrasounds.mixin.ItemPickSound (extrasounds.mixins.json)
		dev.stashy.extrasounds.mixin.HotbarSlotSound (extrasounds.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		ca.fxco.memoryleakfix.mixin.customPayloadLeak.MinecraftClient_freeBufferMixin (memoryleakfix.mixins.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinMinecraft (mixins.jgui.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		shetiphian.core.mixins.SPC_ItemColor_Accessor (shetiphiancore.mixins.json)
		de.keksuccino.drippyloadingscreen.mixin.client.MixinMinecraftClient (drippyloadingscreen.mixin.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		com.replaymod.render.mixin.Mixin_SuppressFramebufferResizeDuringRender (mixins.render.replaymod.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		fi.dy.masa.malilib.mixin.MixinMinecraftClient (mixins.malilib.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		dev.tr7zw.itemswapper.mixin.MinecraftMixin (itemswapper.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		com.blamejared.ambientenvironment.mixin.MixinMinecraft (ambientenvironment.fabric.mixins.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (citresewn-defaults.mixins.json)
		dev.notalpha.dashloader.mixin.main.MinecraftClientMixin (dashloader.mixins.json)
		net.xolt.freecam.mixins.MinecraftClientMixin (freecam.mixins.json)
		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json)
		com.replaymod.core.mixin.MinecraftAccessor (mixins.core.replaymod.json)
		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (sodium.mixins.json)
